# Generated by Django 3.1.3 on 2020-11-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('game', models.CharField(default='Название игры', max_length=128, verbose_name='Name')),
                ('name', models.CharField(default='Турнир', max_length=128, verbose_name='Name')),
                ('datetime_begin', models.DateTimeField(default='2000-01-01 00:00:00', verbose_name='Begin_Date')),
                ('datetime_end', models.DateTimeField(default='2000-01-02 00:00:00', verbose_name='End_Date')),
                ('is_private', models.BooleanField(default=True, verbose_name='Is_Private')),
                ('description', models.CharField(default='Описание турнира', max_length=512, verbose_name='Description')),
                ('rules', models.CharField(default='Правила турнира', max_length=512, verbose_name='Rules')),
                ('picture', models.ImageField(default='media/default.png', upload_to='media/', verbose_name='Image')),
                ('team_limit', models.IntegerField(default=16, verbose_name='Team_Limit')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('prize', models.IntegerField(default=0, verbose_name='Prize')),
                ('manager_id', models.CharField(max_length=16, verbose_name='VK_Id')),
                ('table_type', models.IntegerField(default=0, verbose_name='Table_Type')),
                ('table_data', models.CharField(default='', max_length=1024, verbose_name='Table_Data')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('vk_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='VK_Id')),
                ('nickname', models.CharField(max_length=64, null=True, verbose_name='Nickname')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('steam_profile', models.CharField(max_length=128, null=True, verbose_name='Steam_Profile')),
                ('battle_net_profile', models.CharField(max_length=128, null=True, verbose_name='Battle_net_Profile')),
                ('achievements', models.ManyToManyField(blank=True, to='cyberapp.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberapp.contest')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyberapp.player')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='players',
            field=models.ManyToManyField(through='cyberapp.Participation', to='cyberapp.Player', verbose_name='Players'),
        ),
    ]
