# Generated by Django 3.1.3 on 2020-11-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='game',
            field=models.CharField(default='Название игры', max_length=128, verbose_name='Game'),
        ),
    ]
