# Generated by Django 3.1.3 on 2020-11-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberapp', '0003_auto_20201129_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='contest',
            new_name='contests',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='player',
            new_name='players',
        ),
    ]
